### ISSUE TITLE
Mod name is wrong on SpaceDock

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/ksp-advanced-flybywire#16]
https://spacedock.info/mod/1878

> ABFW Revived (OSX version)

The B and F are swapped, Advanced By Fly Wire. Not a big deal but it does cause the three editions of this mod to sort separately in CKAN.

**Comment by linuxgurugamer** [comment]
Unfortunately, nothing can be done about it, I can't change the name.  I will see if it can be fixed in CKAN

**Comment by linuxgurugamer** [comment]
Or maybe I'll just add a new entry on Spacedock.  Let me know if it can be fixed in the netkan file, otherwise I'll just redo the Spacedock entry

**Comment by HebaruSan** [comment]
Will fix in netkans.

**Comment by linuxgurugamer** [comment]
Thank you
