### ISSUE TITLE
Update for 1.7?

### ISSUE THREAD

**Issue by NoraCodes** [linuxgurugamer/ksp-advanced-flybywire#17]
I'd love to use this but can't use it with 1.7.

**Comment by linuxgurugamer** [comment]
Issues are for bugs, not support. This is a support request, and no info has been given.

 It is better to post messages like this in the forum:

https://forum.kerbalspaceprogram.com/index.php?/topic/175359-15-afbw-revived-joystick-controller-mod/

Also, when asking for help, you should always provide a link to a log file, see this for info on how to get the files:
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

Finally, make sure the dependencies are installed:

Click Through Blocker
ToolbarController

**Comment by NoraCodes** [comment]
Well, don't be _that_ way. I'm well aware of how issues work, and as it turns out, I was _wrong_ about not being able to use it for 1.7; however, I was _not_ asking for support.

As it is, I'm going to submit a PR to make the compatibility list more clear in the README, if that's OK with you.

**Comment by linuxgurugamer** [comment]
Sorry, but I support over 180 mods.  I may be a bit short at times, but I did provide you the info, would have preferred that the request or statement be made in the forum for things like this.

the .version is correct, and I'll look for the PR
