### ISSUE TITLE
Does any version of AFBW support KSP 1.7.3?

### ISSUE THREAD

**Issue by dfbeav** [linuxgurugamer/ksp-advanced-flybywire#24]
I'm attempting to play KSP in VR with a joystick controller. Unfortunately, the VR mod only works for KSP 1.7.x. I can't seem to find a version of AFBW that supports that specific version of KSP, did I happen to miss it?

**Comment by linuxgurugamer** [comment]
https://github.com/linuxgurugamer/ksp-advanced-flybywire/releases/tag/1.8.2.1
