### ISSUE TITLE
Installation instructions in readme are out of date

### ISSUE THREAD

**Issue by jelaby** [linuxgurugamer/ksp-advanced-flybywire#26]
[README.md](https://github.com/linuxgurugamer/ksp-advanced-flybywire/blob/master/README.md)
* links to version 1.7-beta - maybe linking to the releases URL would be better
* does not mention dependencies on Click Through Blocker and ToolbarController

**Comment by linuxgurugamer** [comment]
I kind of wonder how you found it to install in the first place, this is kind of the problem of the "which came first, the chicken or the egg".  I mean, you had to have downloaded it first.
Also, much more complete instructions are on the forum page here:
[https://forum.kerbalspaceprogram.com/index.php?/topic/175359-19x-*](https://forum.kerbalspaceprogram.com/index.php?/topic/175359-19x-*)

That being said, I did just do a minor update, mainly to fix the download link

**Comment by jelaby** [comment]
I found it by following the first download link here on the KSP mod forum page for this plugin here: https://forum.kerbalspaceprogram.com/index.php?/topic/175359-19x-afbw-revived-joystick-controller-mod/ which takes you to https://github.com/linuxgurugamer/ksp-advanced-flybywire where the readme is displayed in full.

To me, the forum page looks out of date, so I followed the first instructions I thought would be up-to-date, which to me would be the Github page that is built out of the latest software.

I'll submit a PR...
