### ISSUE TITLE
Axes behaving badly

### ISSUE THREAD

**Issue by Richard-Payne** [linuxgurugamer/ksp-advanced-flybywire#28]
I'm using an Saitek X-52 Pro and the following 2 issues:

Issue 1:

Axis #3 is a scroll wheel on the throttle which I was attempting to use for trim.  However, it seems that the value mapping is pegged from -1 to 0.  Looking at the Manjaro game controller screen at the same time, the raw input the controller is ranging -32767 to +32767.  When the OS shows it at zero, AFBW's controller configuration screen shows -0.479.  Axis #6 behaves in the same way.  All other axes map -32767 to -1 and +32767 to +1.

Issue 2:

My pitch control is assigned to axis #1.  The config screen correctly ranges from -1 to +1 but the pitch needle at the bottom left of the flight scene behaves oddly. 

Launching from the VAB with a standard rocket, the pitch needle only goes from the middle to the top.  Pulling back on the stick (0 -> 1) raised the pitch needle.  Push forward (0 -> -1) does not move the needle. This obviously makes rockets uncontrollable.  Yaw and Roll axes are fine.

Launching from the SPH with a jet aircraft, the pitch needle is pegged at the bottom when the stick is reading 0 and pulling back to +1 raises the needle to the middle.  Yaw behaves the same way. Roll still works fine.

In both cases, using the Invert option does not change the pegged range but does change the direction in which the stick must be pushed to range the needle.

KSP.log file here: https://gist.github.com/Richard-Payne/c401e9656456e5e31a73697c91816bbd

Although the content does not seem particularly useful in this case.  Let me know if you'd like more detailed logging and, if so, how to enable it.

**Comment by linuxgurugamer** [comment]
Did you calibrate it first?

**Comment by Richard-Payne** [comment]
yes

**Comment by Richard-Payne** [comment]
But that said, I clearly did it wrong in some way.  Have just re-done it and the issues seem to have gone.

**Comment by linuxgurugamer** [comment]
Ah.  Ok, I'll close it, but what I have found is that when doing the throttle, I have to have it closed when starting the calibration (different joystick).  Could be something along that line.
Thanks for updating

**Comment by Richard-Payne** [comment]
Can we re-open this please.  I just booted the game up and the controls were all over the place.  I went through the calibration process again and it's most worked but issue 2 is back.  I've tried multiple calibrations but nothing seems to make the pitch needle map to axis #1 properly.

**Comment by Richard-Payne** [comment]
ok, and then revert to launch fixed it again.  There's definitely something odd going on here but I've not managed to re-produce to it consistently.
