### ISSUE TITLE
Discrete throttle input not functional

### ISSUE THREAD

**Issue by allmhuran** [linuxgurugamer/ksp-advanced-flybywire#34]
Keys bound to discrete throttle controls appear to have no effect. All other keys I have tried binding work as expected.

KSP version: 1.12.1.3124 windows 64 bit
afbw version: 1.8.3.3

Non functional inputs: Throttle+, Throttle-, Cut Throttle, Full Throttle (screenshot)

I do have atmospheric autopilot installed, but the behaviour is the same with any combinations of AA's "master switch" on or off, and AFBW's "AtmosphereAutopilot Compatibility" on or off, "override throttle" on or off, and "override sas and other control inputs" on or off.

![abfw_throttle](https://user-images.githubusercontent.com/7334974/125535006-db0681cd-012c-418c-bc47-d04857f9d962.png)

**Comment by linuxgurugamer** [comment]
> I ran into this issue too. It seems to be possible to work around it by adding and then removing a throttle axis (bound to any axis).
> 
> (thanks very much for maintaining this! It was a breeze to get setup and working for all the other buttons)

This will be very helpful in debugging, thanks

**Comment by linuxgurugamer** [comment]
I've been able to (finally) replicate this

**Comment by TimothyJones** [comment]
This is great news! Thanks for looking in to it so promptly!

**Comment by linuxgurugamer** [comment]
Fixed in 1.8.4.1
