### ISSUE TITLE
feature: support multiple inputs per control

### ISSUE THREAD

**Issue by azrdev** [linuxgurugamer/ksp-advanced-flybywire#41]
AIUI for each kerbal control, I can only assign one axis/button.

My gamepad Logitech F310 has two analog shoulder buttons that are represented (on ubuntu 20.04, via /dev/event/js0) as two different axis (one going from -1..0, the other from 0..1). I see no way of using these together for one control, and I see no control where I would only ever want to go in one direction.

**Comment by linuxgurugamer** [comment]
In the future, please ask questions on the forum, not here.  I generally do not do support on github

That being the case, I believe that's the way gamepads work, while to you it appears as a single control, to the computer, it's not
