### ISSUE TITLE
Setting Menu Not Fully Loading

### ISSUE THREAD

**Issue by TecboyEngineer** [linuxgurugamer/ksp-advanced-flybywire#44]
OS: macOS Sonoma 14.2.1
Hardware: Logitech Heavy Equipment Side Panel

So when I go onto KSP and I load up a plane to launch on the runway the main configuration menu won't show up. So I went on reddit and saw that other people had the same issue. So I don't know if it is the mod, or my Mac, something I did wrong, and/or the controller. But I was wondering if you could look into that.

PS: Could you post a video on how to install Advanced Flybywire onto a Mac.

Reddit post: https://www.reddit.com/r/KerbalSpaceProgram/comments/s9gb3w/i_have_a_problem_with_a_mod_called_advanced/

**Comment by linuxgurugamer** [comment]
This is a support question, not an issue.
Please ask this on the forum, I do not have a Mac to test with.

**Comment by TecboyEngineer** [comment]
Which Forum

**Comment by linuxgurugamer** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/175359-*

You should also provide a Player.log, and info on how you installed it

**Comment by TecboyEngineer** [comment]
Also you respond really fast

**Comment by linuxgurugamer** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

You happened to catch me before work

**Comment by TecboyEngineer** [comment]
which KSP1 form
