### ISSUE TITLE
Axis trim control change

### ISSUE THREAD

**Issue by KSAMissionCtrl** [linuxgurugamer/ksp-advanced-flybywire#5]
Currently moving the trim axis sets the magnitude of the trim movement. So if I want to adjust my trim a bit I have to “blip” the knob I have assigned to the axis, tweaking it forward and back or back and forward just a bit to make the change.﻿ A better solution, and the way I thought it would work originally, would be to have the position of the axis set the fixed amount of trim.

**Comment by linuxgurugamer** [comment]
The way it is currently working is for buttons, so you would have one button to increase the trim, and another button to decrease the trim.
You are asking for an analog control.  This already exists.  it sounds like you are using the buttons for the Trim+ or Trim-, but if you go to the axis, you have a direct trim control for all the axises:

Yaw (Trim)
Roll (Trim)
Pitch (Trim)

**Comment by KSAMissionCtrl** [comment]
I'm using the axis assigned to knobs on my joystick. This behavior is how the axis control works. The buttons, as described in the thread in [this post](https://forum.kerbalspaceprogram.com/index.php?/topic/175359-14-afbw-revived-joystick-controller-mod/&do=findComment&comment=3387290), don't even work properly at all they just pin the trim at max/min when they are pressed

**Comment by linuxgurugamer** [comment]
Pitch Trim+ and Pitch Trim- are buttons, not axises.  They are working correctly.
You need to use one of the following:

- Yaw (Trim)
- Roll (Trim)
- Pitch (Tr

im)
which are found when adding an axis control

**Comment by linuxgurugamer** [comment]
See the latest update:
	Centered Mod Settings button
	Fixed RadialIn/RadialOut buttons (are reversed)
	Fixed Pitch Trim +/- to adjust trim by .1 per click
If you have other specific problems, first check in the forum for support before opening an issue here, thanks.

**Comment by KSAMissionCtrl** [comment]
wait wait where is the confusion here? I apologize if I've been unclear. I've said repeatedly I'm using the trim *axis* not the buttons. Great to hear you fixed the buttons but these are two separate issues. Here is an image of my current trim setup:

![ksp_x64 exe_dx9_20180601_215555](https://user-images.githubusercontent.com/18425575/40865186-1ce4ed6a-65c5-11e8-94ff-418d88b5f0e5.png)

and this is where they are assigned to on my X55 HOTAS:

![untitled](https://user-images.githubusercontent.com/18425575/40863601-745e42a0-65be-11e8-8033-da7834240c2f.png)

The top knob is yaw the bottom is pitch. If I twist either of the knobs a bit, the assigned trim axis begins to move slowly. If I twist the knobs further the trim axis moves faster. So the further the axis off center the faster the trim setting is adjusted. I'm asking for it to instead be if I have the knob twisted only halfway that means the trim is set only halfway. That allows for much finer control than having to "blip" the knob if I only want to increase my trim a hair. I don't know about stock but my aircraft built with FAR are all *extremely* sensitive to small trim changes, even if I have the deflection tweakable set fairly low for the control surface.

I also just had the realization, literally just now as I finish typing all this, that maybe the trim axis was designed this way because it was meant to *augment* the trim buttons. So the trim buttons let you make very minute trim adjustments, while the axis let you make larger ones without have to hold the button down and wait. The buttons being broken all this time, I never really thought of this since I never used them.

But in that case 10% change per button click is way to much and should be more like 1%

**Comment by linuxgurugamer** [comment]
The trim used to be 100%, my fix was to reduce that to 10%.
But it sounds like you want it lower, or at least the ability to control how much the buttons would do.  

Keep in mind that whatever I do, needs to accommodate people who only use one or the other. 
Please test it as it is now, and let me know if the current functionality is working, then I can think about improvements

**Comment by KSAMissionCtrl** [comment]
> needs to accommodate people who only use one or the other.

what I was trying to say is that I don't think it was originally designed to be used as one or the other. Wish the original author was still around so we could find out. If the trim button hadn't been bugged to go max in either direction it would have paired well with the axis. Actually thinking of it more maybe the trim button wasn't bugged and instead it was supposed to be a shortcut to max/min trim from which you would then use the axis to more precisely set? Well, you've seen the code maybe you have an opinion on whether it was a bug or not. I think we need more opinions from other users on this. I'm taking it to the thread

**Comment by linuxgurugamer** [comment]
Yes. it can.
Now, I'll check this when I get home this evening, but it appeared that it was already doing that, although it seemed to be overly sensitive. Can you try it, adjust the trim (do it with pitch) to be neutral, then very gently move it slightly in one direction?

And feel free to bring this up in the thread.  This is a feature I don't use, so I'll be depending on your and other people's feedback

**Comment by KSAMissionCtrl** [comment]
> Can you try it, adjust the trim (do it with pitch) to be neutral, then very gently move it slightly in one direction?

Not until tomorrow, but I will

**Comment by KSAMissionCtrl** [comment]
ok I installed ksp 1.4.3 and tested and yea, the axis controls travel speed of the trim, not position. Was sure I hadn't seen any notes from any releases that mentioned a change to this behavior from 1.3.1. However I also found the trim +/- buttons to be very small adjustments per click. When you said the buttons had been pinning to 100% and had set it to travel at 10% I thought that meant it would only take 10 clicks to set full trim but it takes way more than that. I can't fully test with the aircraft I fly regularly because FAR is still not ready for 1.4 but I think the current button click travel would be good enough for the small adjustments I need that is tough to do with a blip of the trim axis. If anyone complains about the button adjustment size and doesn't have extra axis to use for trim you may want to consider just making it user-adjustable

**Comment by Tr0llmops** [comment]
I just got myself an X52 HOTAS and now I'm struggling with the same issue.

The current behaviour seems to be designed for people who use the main joystick axes (X or Y) for adjusting trim. Those automatically reset to 0 when you let go, and that's the only way the current implementation is usable: nudge the axis until the desired trim is reached and then just let it go.
However, this is completely unusable when trying to map the trim to knob controls (as shown in https://github.com/linuxgurugamer/ksp-advanced-flybywire/issues/5#issuecomment-394020325), which is what I'm trying to do. In order to adjust trim, I now have to carefully turn the knob in both directions instead of just one, zeroing in manually and trying not to overshoot. It just sucks.

What I need is just what was suggested earlier: "Can the axis value be mapped directly to the trim value? So if I twist the knob halfway I get half trim?"
My suggestion is to just add this option as new axes, e.g. "Pitch (Trim Absolute)". This way, it wouldn't interfere with the existing implementation und would allow both options.

I would be grateful if you'd consider reopening this issue.

Thank you!
