### ISSUE TITLE
HOW TO: Install on OSX

### ISSUE THREAD

**Issue by armandfardeau** [linuxgurugamer/ksp-advanced-flybywire#7]
Hi, I want to share my issue and how I manage to fix it.
I installed AFBW on OSX High Sierra with KSP 1.4.5 using CKAN.

All went fine except when in game, the AFBW window appear empty : 
![image](https://user-images.githubusercontent.com/20232956/44577559-be52e400-a791-11e8-90ab-e68a08e40796.png)

The debug window says a dependancy was missing, 

I fixed it with `brew install sdl2` and restart the game.

On second launch : 

![image](https://user-images.githubusercontent.com/20232956/44578488-0a068d00-a794-11e8-8eac-0a6da728bfbd.png)

Good luck for all and thanks to you @linuxgurugamer.

**Comment by linuxgurugamer** [comment]
Thank you, I'll try to get the instructions updated

**Comment by traisjames** [comment]
Just so you know the instructions are still not updated on the mod pages.

**Comment by linuxgurugamer** [comment]
Updated this evening

**Comment by whale2-spread** [comment]
For anyone trying to run it on Apple Silicone - 

Take this DLL: https://github.com/OutOfOrder/SDL2-Binaries/blob/master/osx/libSDL2.dylib
(I had hard time convincing brew to install x86 version, so this is a ready-made x86_64 binary)
Put it anywhere you like
Rename it as libSDL2-2.0.14.dylib
Add `export DYLD_LIBRARY_PATH=<the path you put it>`
