### ISSUE TITLE
OSX throttle uses only half the range

### ISSUE THREAD

**Issue by matyee** [linuxgurugamer/ksp-advanced-flybywire#9]
I have a Saitek X52 pro H.O.T.A.S. I could not map the axis with the stock game, it would not save my settings. It worked perfectly with this mod. My only problem is that the throttle uses only half the range. KSP keeps the throttle on zero from 0% to 50% and only starts to actually increase the throttle once I am above 50%. The calibration show the throttle range from -1 to 1. I think this is the problem, maybe it should be going from 0 to 1. I could not figure out a way to solve this issue. What can I do? Is there any way to get over this problem?

**Comment by linuxgurugamer** [comment]
First, set the throttle to 0, then recalibrate it.
Let me know how it goes, if it still doesn't work, I'll have to do some research

**Comment by matyee** [comment]
Hey @linuxgurugamer, thanks for yout reply. I did what you recommended and it is now working fine. I think I tried having the throttle at zero when I started the game, but probably I never calibrated. Beeing able to use the whole range of the throttle is amazing :)
